# airline_codes.py

"""
Ce fichier agit en tant que dictionnaire, permettant de pouvoir identifier plus facilement les compagnies autrement que par leurs
codes IATA
"""

airline_codes = {
    'AA': 'American Airlines (États-Unis)',
    'AB': 'Air Berlin (Allemagne)',
    'AC': 'Air Canada (Canada)',
    'AD': 'Azul Brazilian Airlines (Brésil)',
    'AE': 'Mandarin Airlines (Taïwan)',
    'AF': 'Air France (France)',
    'AG': 'Aruba Airlines',
    'AH': 'Air Algérie (Algérie)',
    'AI': 'Air India',
    'AJ': 'AeroContractors of Nigeria (Nigeria)',
    'AK': 'Air Asia Sen (Malaisie)',
    'AL': 'Malta Air (Malte)',
    'AM': 'Aeroméxico Aerovias de Mexico (Mexique)',
    'AN': 'Andorra Airlines',
    'AO': 'Australian Airlines (Australie)',
    'AP': 'Albastar (Espagne)',
    'AQ': '9 Air (Chine)',
    'AR': 'Aerolíneas Argentinas (Argentine)',
    'AS': 'Alaska Airlines (États-Unis)',
    'AT': 'Royal Air Maroc (Maroc)',
    'AU': 'Austral Líneas Aéreas-Cielos del Sur (Argentine)',
    'AV': 'Avianca (Colombie)',
    'AX': 'Trans States Airlines (États-Unis)',
    'AY': 'Finnair (Finlande)',
    'AZ': 'ITA Airways (Italie)',
    'A0': 'L\'Avion (France)',
    'A2': 'Astra Airlines (Grèce)',
    'A3': 'Aegean Airlines (Grèce)',
    'A4': 'Southern Winds (Argentine)',
    'A5': 'HOP! (France)',
    'A6': 'Asia Pacific Airlines (Guam)',
    'A8': 'Benin Golf Air (Bénin)',
    'A9': 'Georgian Airlines (Géorgie)',
    'BA': 'British Airways (Royaume-Uni)',
    'BC': 'Skymark Airlines (Japon)',
    'BD': 'Cambodia Bayon Airlines (Cambodge)',
    'BE': 'flyBe (Royaume-Uni)',
    'BF': 'French Bee',
    'BG': 'Biman Bangladesh Airlines (Bangladesh)',
    'BI': 'Royal Brunei Airlines (Brunei)',
    'BJ': 'Nouvelair Tunisia (Tunisie)',
    'BK': 'OKAir (Chine)',
    'BL': 'Pacific Airlines (Viêt Nam)',
    'BM': 'BMI Regional (Royaume-Uni)',
    'BN': 'Forward Air International Airlines (États-Unis)',
    'BO': 'Bouraq Indonesia Airlines (Indonésie)',
    'BP': 'Air Botswana Corp (Botswana)',
    'BQ': 'Aeromar Airlines (République dominicaine)',
    'BR': 'EVA Airways (Taïwan)',
    'BS': 'British International Helicopters (Royaume-Uni)',
    'BT': 'Air Baltic (Lettonie)',
    'BU': 'Bural (Russie)',
    'BV': 'Blue Panorama Airlines (Italie)',
    'BW': 'Carribean Airlines',
    'BX': 'Air Busan',
    'BY': 'Thomsonfly (Royaume-Uni)',
    'BZ': 'Blue Dart Aviation (Inde)',
    'B0': 'La Compagnie Boutique Airline',
    'B2': 'Belavia (Biélorussie)',
    'B3': 'Bellview Airlines (Nigeria)',
    'B4': 'Bankair (États-Unis)',
    'B5': 'Fly-SAX (Kenya)',
    'B6': 'jetBlue Airways (États-Unis)',
    'B7': 'UNI Airways (Taïwan)',
    'B8': 'Eritrean Airlines (Érythrée)',
    'B9': 'Iran Air Tours (Iran)',
    'CA': 'Air China Ltd (Chine)',
    'CB': 'Scot Airways (Royaume-Uni)',
    'CC': 'Macair Airlines (Australie)',
    'CD': 'Corendon Dutch Airlines (Pays-Bas)',
    'CE': 'Chalair Aviation (France)',
    'CF': 'China Postal Airlines (Chine)',
    'CG': 'Airlines PNG (Papouasie-Nouvelle-Guinée)',
    'CH': 'Bemidji Airlines (États-Unis)',
    'CI': 'China Airlines (Taïwan)',
    'CJ': 'BA CityFlyer (Royaume-Uni)',
    'CL': 'Lufthansa CityLine GmbH (Allemagne)',
    'CM': 'Copa Airlines (Panama)',
    'CN': 'Grand China Air (Chine)',
    'CO': 'Cobalt Air (Chypre)',
    'CQ': 'Coastal Travels Ltd. (Tanzanie)',
    'CR': 'OAG Worldwide (Royaume-Uni)',
    'CS': 'Continental Micronesia',
    'CT': 'ALITALIA CITY LINER SPA',
    'CU': 'Cubana (Cuba)',
    'CV': 'Cargolux',
    'CW': 'Air Marshall Islands',
    'CX': 'Cathay Pacific Airways (Hong Kong)',
    'CY': 'Charlie Airlines (Chypre)',
    'CZ': 'China Southern Airlines (Chine)',
    'C0': 'Centralwings (Pologne)',
    'C2': 'CEIBA Intercontinental',
    'C3': 'Trade Air Ltd. (Croatie)',
    'C4': 'SVG Air (Saint-Vincent et les Grenadines)',
    'DB': 'Brit Air (France)',
    'DC': 'Golden Air',
    'DD': 'Nok Air',
    'DE': 'Condor Flugdienst (Allemagne)',
    'DH': 'Independence Air (États-Unis)',
    'DI': 'Deutsche BA Luftfahrtgesellschaft mbH (Allemagne)',
    'DJ': 'AirAsia Japan (Japon)',
    'DK': 'Eastland Air',
    'DL': 'Delta Air Lines (États-Unis)',
    'DM': 'Asian Air',
    'DN': 'Simplify Deccan (Inde)',
    'DO': 'Sky High Aviation Services (République Dominicaine)',
    'DP': 'Pobeda (Russie)',
    'DQ': 'Coastal Air Transport',
    'DR': 'Ruili Airlines (Chine)',
    'DS': 'EasyJet Switzerland (Suisse)',
    'DT': 'TAAG Angola Airlines (Angola)',
    'DV': 'Nantucket Airlines (Nouvelle-Angleterre)',
    'DW': 'Aero-Charter Airlines (Ukraine)',
    'DX': 'Danish Air Transport (Danemark)',
    'DY': 'Norwegian',
    'DZ': 'Donghai Airlines (Chine)',
    'D0': 'DHL Air UK Ltd',
    'D3': 'Daallo Airlines (Somalie et Djibouti)',
    'D7': 'AirAsia X (Malaysia)',
    'D8': 'Norwegian Air International',
    'D9': 'Donavia (Russie)',
    'E2': 'Eurowings Europe (Autriche)',
    'EA': 'Eastern Airlines',
    'EB': 'Wamos Air (Espagne)',
    'EC': 'easyJet Europe (Autriche)',
    'ED': 'AirExplore (Slovaquie)',
    'EE': 'Xfly (Estonie)',
    'EG': 'Japan Asia Airways (Japon)',
    'EH': 'ANA Wings (Japon)',
    'EI': 'Aer Lingus (Irlande)',
    'EJ': 'European Cargo Services B.V.',
    'EK': 'Emirates (Émirats arabes unis)',
    'EL': 'Ellinair',
    'EN': 'Air Dolomiti (Italie)',
    'EO': 'Hewa Bora Airways (République démocratique du Congo)',
    'EP': 'Iran Aseman Airlines (Iran)',
    'EQ': 'TAME (Équateur)',
    'ER': 'Serene Air (Pakistan)',
    'ES': 'DHL International EC (Bahreïn)',
    'ET': 'Ethiopian Airlines (Éthiopie)',
    'EU': 'Chengdu Airlines (Chine)',
    'EV': 'Atlantic Southeast Airlines (États-Unis)',
    'EW': 'Eurowings AG (Allemagne)',
    'EX': 'Thai Express Air',
    'EY': 'Etihad Airways (Émirats arabes unis)',
    'EZ': 'Sun Air of Scandinavia',
    'E3': 'Domodedovo Airlines (Russie)',
    'E4': 'Enter Air (Pologne)',
    'E5': 'Samara Airlines (Russie)',
    'E7': 'Equaflight (République du Congo)',
    'E8': 'City Airways (Thaïlande)',
    'E9': 'Boston-Maine Airways (États-Unis)',
    'FA': 'Safair (Afrique du Sud)',
    'FB': 'Bulgaria Air (Bulgarie)',
    'FC': 'VivaColombia (Colombie)',
    'FD': 'Thai Air Asia (Malaisie-Thaïlande)',
    'FE': 'Far Eastern Air Transport (Taïwan)',
    'FG': 'Ariana Afghan Airlines (Afghanistan)',
    'FH': 'Free Bird Airlines (Turquie)',
    'FI': 'Icelandair (Islande)',
    'FJ': 'Fiji Airways (Fidji)',
    'FK': 'Kelowna Flightcraft Air Charter (Canada)',
    'FL': 'Flybi Airways (France)',
    'FM': 'Shanghai Airlines (Chine)',
    'FN': 'Regional Airlines (Maroc)',
    'FO': 'Felix Airways (Yémen)',
    'FP': 'Freedom Air (États-Unis, Guam)',
    'FR': 'Ryanair (Irlande)',
    'FS': 'Syphax Airlines (Tunisie)',
    'FT': 'FlyEgypt (Égypte)',
    'FU': 'Fuzhou Airlines (Chine)',
    'FV': 'Pulkovo Aviation Enterprise (Russie)',
    'FW': 'Ibex Airlines (Japon)',
    'FX': 'Federal Express Corp ou FedEx (États-Unis)',
    'FY': 'Firefly (Malaisie)',
    'FZ': 'Flydubai (Émirats arabes unis)',
    'F2': 'Safarilink Aviation (Kenya)',
    'F5': 'Cosmic Air (Népal)',
    'F7': 'Darwin Airline (Suisse)',
    'F9': 'Frontier Airlines (États-Unis)',
    'GA': 'Garuda Indonesia (Indonésie)',
    'GC': 'Gambia International Airlines (Gambie)',
    'GE': 'Transasia Airways (Taïwan)',
    'GF': 'Gulf Air (Bahreïn)',
    'GH': 'Ghana Airways (Ghana)',
    'GJ': 'Eurofly (Italie)',
    'GK': 'Jetstar Japan (Japon)',
    'GM': 'Tri-MG Intra Asia Airlines (Indonésie)',
    'GN': 'Air Gabon (Gabon)',
    'GP': 'APG Airlines (France)',
    'GS': 'Tianjin Airlines (Chine)',
    'GT': 'GB Airways (Royaume-Uni)',
    'GU': 'Aviateca (Guatemala)',
    'GW': 'SkyGreece Airlines (Grèce)',
    'GX': 'JetX Airlines (Islande/Italie)',
    'GZ': 'Air Rarotonga (Îles Cook)',
    'G4': 'Allegiant Air (États-Unis)',
    'G5': 'China Express Airlines (Chine)',
    'G7': 'Gandalf Airlines (Italie)',
    'G8': 'GoAir (Inde)',
    'HA': 'Hawaiian Airlines (États-Unis)',
    'HB': 'Asia Atlantic Airlines (Thaïlande)',
    'HC': 'Air Sénégal (Sénégal)',
    'HD': 'Hokkaido International Airlines ou Air Do (Japon)',
    'HE': 'LGW - Luftfahrtgesellschaft Walter (Allemagne)',
    'HF': 'Air Côte d\'Ivoire (Côte d\'Ivoire)',
    'HG': 'Niki (Autriche)',
    'HH': 'Islandsflug (Islande)',
    'HJ': 'Tasman Cargo Airlines (Australie)',
    'HM': 'Air Seychelles (Seychelles)',
    'HO': 'Juneyao Airlines (Chine)',
    'HR': 'Hahn Air Lines (Allemagne)',
    'HT': 'Aeromist-Kharkiv (Ukraine)',
    'HU': 'Hainan Airlines (Chine)',
    'HV': 'Transavia (Pays-Bas)',
    'HW': 'North-Wright Airways (Canada)',
    'HX': 'Hong Kong Airlines (Hong Kong)',
    'HY': 'Uzbekistan Airways (Ouzbékistan)',
    'HZ': 'Aurora Airlines (Russie)',
    'H2': 'Sky Airline (Chili)',
    'H5': 'Magadan Airlines (Russie)',
    'H8': 'Dalavia (Russie)',
    'H9': 'Himalaya Airlines (Népal)',
    'IA': 'Iraqi Airways (Irak)',
    'IB': 'Iberia (Espagne)',
    'ID': 'Batik Air (Indonésie)',
    'IE': 'Solomon Airlines (Îles Salomon)',
    'IG': 'Meridiana (Italie)',
    'IH': 'Falcon Air (Suède)',
    'IJ': 'Spring Airlines Japan (Japon)',
    'IK': 'Pegas Fly (Russie)',
    'IL': 'Trigana Air Service (Indonésie)',
    'IN': 'MAT Macedonian Airlines (Macédoine)',
    'IO': 'IrAero (Russie)',
    'IP': 'Apsara International Air (Cambodge)',
    'IQ': 'Augsburg Airways (Allemagne)',
    'IR': 'Iran Air (Iran)',
    'IT': 'Tigerair Taiwan (Taïwan)',
    'IV': 'Wind Jet (Italie)',
    'IW': 'Wings Air (Indonésie)',
    'IX': 'Air India Express (Inde)',
    'IY': 'Yemenia (Yémen)',
    'IZ': 'Arkia Israeli Airlines (Israël)',
    'I2': 'Iberia Express (Espagne)',
    'I4': 'I-Fly (Russie)',
    'I5': 'AirAsia India (Inde)',
    'I9': 'Air Italy (Italie)',
    'JB': 'Helijet (Canada)',
    'JD': 'Beijing Capital Airlines (Chine)',
    'JE': 'Mango Airlines (Afrique du Sud)',
    'JF': 'Jet Asia Airways (Thaïlande)',
    'JH': 'Harlequin Air (Japon)',
    'JJ': 'LATAM Brazil',
    'JL': 'Japan Airlines (Japon)',
    'JN': 'Joon (France)',
    'JO': 'Jasmin Airways (Tunisie)',
    'JP': 'Adria Airways (Slovénie)',
    'JQ': 'Jetstar Airways (Australie)',
    'JR': 'Aero California (Mexique)',
    'JS': 'Air Koryo (Corée du Nord)',
    'JT': 'Lion Air (Indonésie)',
    'JU': 'Air Serbia (Serbie)',
    'JW': 'Vanilla Air (Japon)',
    'JX': 'Jambojet (Kenya)',
    'JY': 'InterCaribbean Airways (Îles Turques-et-Caïques)',
    'JZ': 'Skyways AB (Suède)',
    'J2': 'Azerbaijan Airlines (Azerbaïdjan)',
    'J7': 'Centre-Avia (Russie)',
    'KA': 'Cathay Dragon (Hong Kong)',
    'KB': 'Druk Air (Bhoutan)',
    'KC': 'Air Astana (Kazakhstan)',
    'KD': 'Kal Star (Indonésie)',
    'KF': 'Air Belgium (Belgique)',
    'KE': 'Korean Air (Corée du Sud)',
    'KK': 'Atlasjet (Turquie)',
    'KL': 'KLM Royal Dutch Airlines (Pays-Bas)',
    'KM': 'Air Malta (Malte)',
    'KN': 'China United Airlines (Chine)',
    'KP': 'Asky Airlines (Togo)',
    'KQ': 'Kenya Airways (Kenya)',
    'KR': 'Birgenair (Turquie)',
    'KU': 'Kuwait Airways (Koweït)',
    'KV': 'Kavminvodyavia (Russie)',
    'KW': 'Kelowna Flightcraft',
    'KZ': 'Nippon Cargo Airlines (Japon)',
    'K6': 'Cambodia Angkor Air (Cambodge)',
    'K8': 'Kaliningradavia (Russie)',
    'LA': 'LATAM Chile',
    'LC': 'ECAir (République du Congo)',
    'LD': 'Air Hong Kong (Hong Kong)',
    'LF': 'Fly Nordic (Suède)',
    'LG': 'Luxair (Luxembourg)',
    'LH': 'Lufthansa (Allemagne)',
    'LI': 'Liat (Antigua-et-Barbuda)',
    'LJ': 'Jin Air (Corée du Sud)',
    'LK': 'Air Luxor (Portugal)',
    'LL': 'Miami Air International (États-Unis)',
    'LM': 'Livingston (Italie)',
    'LN': 'Libyan Airlines (Libye)',
    'LO': 'LOT Polish Airlines (Pologne)',
    'LP': 'LATAM Perú (Pérou)',
    'LQ': 'Air Lanmei (Cambodge)',
    'LR': 'Avianca Costa Rica (Costa Rica)',
    'LS': 'Jet2 (Royaume-Uni)',
    'LT': 'Air Lituanica (Lituanie)',
    'LV': 'Level (Espagne)',
    'LW': 'Pacific Wings (États-Unis)',
    'LX': 'SWISS (Suisse)',
    'LY': 'El Al (Israël)',
    'LZ': 'Swiss Global Air Lines',
    'L2': 'Lynden Air Cargo (États-Unis)',
    'L3': 'DHL de Guatemala (Guatemala)',
    'L5': 'Atlas Atlantique Airlines',
    'L7': 'LANCO (Colombie)',
    'L8': 'Afric Aviation (Gabon)',
    'L6': 'Air Mauritanie (Mauritanie)',
    'MA': 'Malév Hungarian Airlines (Hongrie)',
    'MB': 'MNG Cargo Airlines',
    'MC': 'Air Cairo (Égypte)',
    'MD': 'Madagascar Airlines (Madagascar)',
    'ME': 'Middle East Airlines (Liban)',
    'MF': 'Xiamen Airlines (Chine)',
    'MH': 'Malaysia Airlines (Malaisie)',
    'MI': 'SilkAir (Singapour)',
    'MJ': 'MyWay Airlines (Géorgie)',
    'MK': 'Air Mauritius (Maurice)',
    'ML': 'Air Méditerranée (France)',
    'MM': 'Peach Aviation (Japon)',
    'MN': 'Kulula (Afrique du Sud)',
    'MP': 'Martinair Holland (Pays-Bas)',
    'MQ': 'American Eagle (États-Unis)',
    'MR': 'Air Mauritanie (Mauritanie)',
    'MS': 'EgyptAir (Égypte)',
    'MT': 'Thomas Cook Airlines (Royaume-Uni)',
    'MU': 'China Eastern Airlines (Chine)',
    'MV': 'Aviastar (Indonésie)',
    'M0': 'Aero Mongolia (Mongolie)',
    'M8': 'TransNusa Air Services (Indonésie)',
    'M9': 'Motor Sich (Ukraine)',
    'NC': 'Northern Air Cargo (États-Unis)',
    'NE': 'Sky Europe Airlines (Slovaquie)',
    'NF': 'Air Vanuatu (Vanuatu)',
    'NG': 'Lauda Air (Autriche)',
    'NH': 'All Nippon Airways (Japon)',
    'NK': 'Spirit Airlines (États-Unis)',
    'NL': 'Amelia International (Slovénie)',
    'NQ': 'Air Japan (Japon)',
    'NT': 'Binter Canarias (Espagne)',
    'NU': 'Japan Transocean Air (Japon)',
    'NW': 'Celeste (France)',
    'NX': 'Air Macau (Macao, Chine)',
    'NZ': 'Air New Zealand (Nouvelle-Zélande)',
    'N2': 'Aerolineas Internacionales (Mexique)',
    'N3': 'Omskavia Airlines (Russie)',
    'N4': 'Nordwind Airlines (Russie)',
    'N5': 'Flyeasy (Inde)',
    'N6': 'Nuevo Continente (Pérou)',
    'N7': 'Lagun Air (Espagne)',
    'OA': 'Olympic Airlines (Grèce)',
    'OB': 'Boliviana de Aviación (Bolivie)',
    'OC': 'Oriental Air Bridge (Japon)',
    'OD': 'Malindo Air (Malaisie)',
    'OE': 'Cairo Aviation (Égypte)',
    'OF': 'Air Finland (Finlande)',
    'OG': 'One-Two-Go Airlines (Thaïlande)',
    'OH': 'Comair Inc. (États-Unis)',
    'OJ': 'Fly Jamaica Airways',
    'OK': 'Czech Airlines (République tchèque)',
    'OL': 'OLT Express Germany (Allemagne)',
    'OM': 'MIAT Mongolian Airlines (Mongolie)',
    'ON': 'Our Airline (Nauru)',
    'OO': 'SkyWest Airlines (États-Unis)',
    'OQ': 'Chongqing Airlines (Chine)',
    'OR': 'TUI fly Netherlands (Pays-Bas)',
    'OS': 'Austrian Airlines (Autriche)',
    'OT': 'Tchadia Airlines (Tchad)',
    'OU': 'Croatia Airlines (Croatie)',
    'OV': 'Estonian Air (Estonie)',
    'OW': 'Executive Airlines (États-Unis)',
    'OX': 'Orient Thai Airlines (Thaïlande)',
    'OY': 'Omni Air International (États-Unis)',
    'OZ': 'Asiana Airlines (Corée du Sud)',
    'O3': 'SF Airlines (Chine)',
    'O6': 'Avianca Brazil (Brésil)',
    'O7': 'OzJet (Australie)',
    'PA': 'Airblue (Pakistan)',
    'PB': 'Provincial Airlines (Canada)',
    'PC': 'Pegasus Airlines (Turquie)',
    'PD': 'Porter Airlines (Canada)',
    'PE': 'Air Europe (Italie)',
    'PF': 'Primera Air (Danemark)',
    'PG': 'Bangkok Airways (Thaïlande)',
    'PH': 'Polynesian Airlines (Samoa)',
    'PJ': 'Air Saint-Pierre (Saint-Pierre-et-Miquelon)',
    'PK': 'Pakistan International Airlines (Pakistan)',
    'PL': 'AeroPeru (Pérou)',
    'PM': 'Tropic Air (Belize)',
    'PO': 'Polar Air Cargo (États-Unis)',
    'PR': 'Philippine Airlines (Philippines)',
    'PS': 'Ukraine International Airlines (Ukraine)',
    'PT': 'West Atlantic (Suède)',
    'PU': 'Pluna (Uruguay)',
    'PV': 'Privatair (Suisse)',
    'PW': 'Precision Air (Tanzanie)',
    'PX': 'Air Niugini (Papouasie-Nouvelle-Guinée)',
    'PY': 'Surinam Airways (Suriname)',
    'PZ': 'Paranair (Paraguay)',
    'P5': 'AeroRepublica (Colombie)',
    'P7': 'Small Planet Airlines (Lituanie)',
    'P8': 'PAG Connexair (États-Unis)',
    'P9': 'PAG Airways (États-Unis)',
    'QA': 'Cimber (Danemark)',
    'QB': 'Sky Georgia (Géorgie)',
    'QC': 'Camair-Co (Cameroun)',
    'QD': 'Air Class Lineas Aereas (Uruguay)',
    'QE': 'Crossair Europe (France)',
    'QF': 'Qantas Airways (Australie)',
    'QG': 'Citilink (Indonésie)',
    'QH': 'Bamboo Airways (Vietnam)',
    'QI': 'Cimber Air (Danemark)',
    'QK': 'Jazz Aviation (Canada)',
    'QM': 'Air Malawi (Malawi)',
    'QO': 'Quikjet Cargo (Inde)',
    'QQ': 'Alliance Airlines (Australie)',
    'QR': 'Qatar Airways (Qatar)',
    'QS': 'SmartWings (République tchèque)',
    'QY': 'European Air Transport Leipzig (Allemagne)',
    'QZ': 'Indonesia AirAsia (Indonésie)',
    'Q3': 'Zambian Airways (Zambie)',
    'Q8': 'Trans Air Congo (République du Congo)',
    'RA': 'Nepal Airlines (Népal)',
    'RB': 'Syrian Air (Syrie)',
    'RC': 'Atlantic Airways (Îles Féroé)',
    'RD': 'Alitalia Team',
    'RE': 'Stobart Air (Irlande)',
    'RF': 'Florida West International Airways (États-Unis)',
    'RG': 'Rotana Jet (Abu Dhabi)',
    'RJ': 'Royal Jordanian (Jordanie)',
    'RK': 'Ryanair UK',
    'RM': 'Air Moldova (Moldavie)',
    'RN': 'Air Horizons (France)',
    'RO': 'TAROM (Roumanie)',
    'RP': 'Chautauqua Airlines (États-Unis)',
    'RQ': 'Kam Air (Afghanistan)',
    'RT': 'UVT Aero (Russie)',
    'RU': 'AirBridgeCargo (Russie)',
    'RV': 'Air Canada Rouge (Canada)',
    'R2': 'Orenair (Russie)',
    'R3': 'Yakutia Airlines (Russie)',
    'R4': 'Russia Airline',
    'R7': 'Aserca Airlines (Venezuela)',
    'SA': 'South African Airways (Afrique du Sud)',
    'SB': 'Aircalin (Nouvelle-Calédonie)',
    'SC': 'Shandong Airlines (Chine)',
    'SD': 'Sudan Airways (Soudan)',
    'SE': 'XL Airways France (France)',
    'SG': 'SpiceJet (Inde)',
    'SH': 'Sharp Airlines (Australie)',
    'SI': 'Susi Air (Indonésie)',
    'SJ': 'Sriwijaya Air (Indonésie)',
    'SK': 'Scandinavian Airlines (Suède/Norvège/Danemark)',
    'SL': 'Thai Lion Air (Thaïlande)',
    'SN': 'Brussels Airlines (Belgique)',
    'SP': 'SATA Air Açores (Portugal)',
    'SQ': 'Singapore Airlines (Singapour)',
    'SS': 'Corsair International (France)',
    'ST': 'Germania (Allemagne)',
    'SU': 'Aeroflot (Russie)',
    'SV': 'Saudi Arabian Airlines (Arabie Saoudite)',
    'SW': 'Air Namibia (Namibie)',
    'SX': 'Sky Work Airlines (Suisse)',
    'SY': 'Sun Country Airlines (États-Unis)',
    'SZ': 'Somon Air (Tadjikistan)',
    'S2': 'Jet Lite (Inde)',
    'S3': 'Santa Barbara Airlines (Venezuela)',
    'S4': 'Azores Airlines (Portugal)',
    'S7': 'S7 Airlines (Russie)',
    'S9': 'East African Safari Air (Kenya)',
    'TA': 'TACA Airlines (Honduras)',
    'TB': 'TUIfly Belgium (Belgique)',
    'TC': 'Air Tanzania (Tanzanie)',
    'TE': 'SkyTaxi (Pologne)',
    'TF': 'Braathens Regional Aviation AB (Suède)',
    'TG': 'Thai Airways International (Thaïlande)',
    'TJ': 'Tradewind Aviation (États-Unis)',
    'TK': 'Turkish Airlines (Turquie)',
    'TM': 'LAM Mozambique Airlines (Mozambique)',
    'TN': 'Air Tahiti Nui (Polynésie française)',
    'TO': 'Transavia France (France)',
    'TP': 'TAP Air Portugal (Portugal)',
    'TQ': 'Tandem Aero (Moldavie)',
    'TR': 'Scoot (Singapour)',
    'TS': 'Air Transat (Canada)',
    'TT': 'Tigerair Australia (Australie)',
    'TU': 'Tunisair (Tunisie)',
    'TW': 'T\'way Air (Corée du Sud)',
    'TX': 'Air Caraïbes (France)',
    'TY': 'Air Calédonie (Nouvelle-Calédonie)',
    'TZ': 'Tsaradia (Madagascar)',
    'T2': 'Lotus Air (Égypte)',
    'T4': 'Hellas Jet (Grèce)',
    'T5': 'Turkmenistan Airlines (Turkménistan)',
    'T6': 'AirSWIFT (Philippines)',
    'T7': 'Twin Jet (France)',
    'UA': 'United Airlines (États-Unis)',
    'UB': 'Myanmar Airways International (Myanmar)',
    'UD': 'Hex\'Air (France)',
    'UF': 'UM Airlines (Ukraine)',
    'UG': 'Tunisair Express (Tunisie)',
    'UI': 'Eurocypria Airlines (Chypre)',
    'UK': 'Vistara (Inde)',
    'UL': 'SriLankan Airlines (Sri Lanka)',
    'UM': 'Air Zimbabwe (Zimbabwe)',
    'UO': 'HK Express (Hong Kong)',
    'UP': 'Bahamasair (Bahamas)',
    'UQ': 'O\'Connor Airlines (Australie)',
    'US': 'US Airways (États-Unis)',
    'UT': 'UTair Aviation (Russie)',
    'UU': 'Air Austral (La Réunion, France)',
    'UW': 'Universal Airlines (Guyana)',
    'UX': 'Air Europa (Espagne)',
    'UY': 'Cameroon Airlines (Cameroun)',
    'U2': 'easyJet (Royaume-Uni)',
    'U3': 'Avies (Estonie)',
    'U5': 'Karinou Airlines (République centrafricaine)',
    'U6': 'Ural Airlines (Russie)',
    'U9': 'Tatarstan Airlines (Russie)',
    'VA': 'Virgin Australia (Australie)',
    'VB': 'VivaAerobus (Mexique)',
    'VD': 'Swedjet Airways (Suède)',
    'VE': 'Avensa (Venezuela)',
    'VG': 'Vipper BV (Pays-Bas)',
    'VH': 'Aeropostal Alas de Venezuela (Venezuela)',
    'VI': 'Volga-Dnepr Airlines (Russie)',
    'VN': 'Vietnam Airlines (Vietnam)',
    'VO': 'Tyrolean Airways (Autriche)',
    'VR': 'TACV Cabo Verde Airlines (Cap-Vert)',
    'VS': 'Virgin Atlantic Airways (Royaume-Uni)',
    'VT': 'Air Tahiti (Polynésie française)',
    'VU': 'Air Ivoire (Côte d\'Ivoire)',
    'VV': 'Aerosvit Airlines (Ukraine)',
    'VY': 'Vueling Airlines (Espagne)',
    'VW': 'Aeromar (Mexique)',
    'VX': 'Virgin America (États-Unis)',
    'VZ': 'Thai VietJet Air (Thaïlande)',
    'V0': 'Conviasa (Venezuela)',
    'V5': 'Danube Wings (Slovaquie)',
    'V7': 'Volotea (Espagne)',
    'V9': 'Bashkir Airlines (Russie)',
    'WA': 'KLM Cityhopper (Pays-Bas)',
    'WB': 'RwandAir (Rwanda)',
    'WE': 'Thai Smile Airways (Thaïlande)',
    'WF': 'Widerøe (Norvège)',
    'WG': 'Sunwing Airlines (Canada)',
    'WI': 'White Airways (Portugal)',
    'WJ': 'Air Labrador (Canada)',
    'WK': 'Edelweiss Air (Suisse)',
    'WM': 'Windward Islands Airways (Winair) (Saint-Martin)',
    'WN': 'Southwest Airlines (États-Unis)',
    'WP': 'Island Air (Hawaii)',
    'WR': 'WestJet Encore (Canada)',
    'WS': 'WestJet (Canada)',
    'WU': 'Wuhan Airlines (Chine)',
    'WW': 'WOW air (Islande)',
    'WY': 'Oman Air (Oman)',
    'WZ': 'Red Wings Airlines (Russie)',
    'WX': 'CityJet (Irlande)',
    'W2': 'Finistair (France)',
    'W5': 'Mahan Air (Iran)',
    'W6': 'Wizz Air (Hongrie)',
    'XC': 'Corendon Airlines (Turquie)',
    'XF': 'Vladivostok Air (Russie)',
    'XG': 'SunExpress Deutschland (Allemagne)',
    'XJ': 'Mesaba Airlines (États-Unis)',
    'XK': 'Air Corsica (France)',
    'XL': 'LATAM Ecuador (Équateur)',
    'XM': 'J-Air (Japon)',
    'XN': 'Xpress Air (Indonésie)',
    'XO': 'LTE International Airways (Espagne)',
    'XQ': 'SunExpress (Turquie/Allemagne)',
    'XT': 'Indonesia AirAsia X (Indonésie)',
    'XU': 'African Express Airways (Somalie/Kenya)',
    'XW': 'NokScoot (Thaïlande)',
    'XY': 'Flynas (Arabie Saoudite)',
    'XZ': 'South African Express Airways (Afrique du Sud)',
    'YC': 'Yamal Airlines (Russie)',
    'YD': 'Mauritania Airways (Mauritanie)',
    'YH': 'Air Nunavut Ltd. (Canada)',
    'YK': 'Cyprus Turkish Airlines (Chypre)',
    'YL': 'Yamal Airlines (Russie)',
    'YM': 'Montenegro Airlines (Monténégro)',
    'YN': 'Air Creebec (Canada)',
    'YO': 'Heli Air Monaco (Monaco)',
    'YP': 'Aero Lloyd (Allemagne)',
    'YQ': 'Polet Airlines (Russie)',
    'YS': 'Régional (France)',
    'YT': 'Air Togo (Togo)',
    'YU': 'EuroAtlantic Airways (Portugal)',
    'YV': 'Mesa Airlines (États-Unis)',
    'YW': 'Air Nostrum (Espagne)',
    'YX': 'Midwest Airlines (États-Unis)',
    'Y4': 'Volaris (Mexique)',
    'Y7': 'NordStar Airlines (Russie)',
    'Y9': 'Kish Air (Iran)',
    'ZA': 'Sky Angkor Airlines (Cambodge)',
    'ZB': 'Monarch Airlines (Royaume-Uni)',
    'ZC': 'Royal Swazi National Airways (Eswatini)',
    'ZD': 'EWA Air (Mayotte)',
    'ZE': 'Eastar Jet (Corée du Sud)',
    'ZH': 'Shenzhen Airlines (Chine)',
    'ZI': 'Aigle Azur (France)',
    'ZL': 'Regional Express (Australie)',
    'ZN': 'Zambia Airways (Zambie)',
    'ZO': 'Zoom Air (Inde)',
    'ZQ': 'German Airways GmbH & Co. KG (Allemagne)',
    'ZU': 'Helios Airways (Chypre)',
    'ZV': 'V Air (Taïwan)',
    'ZY': 'Sky Airlines (Turquie)',
    'Z2': 'AirAsia Philippines (Philippines)',
    'Z6': 'Dniproavia (Ukraine)',
    'Z9': 'Aero Zambia (Zambie)',
    '0B': 'Blue Air (Roumanie)',
    '1A': 'Amadeus IT Group (International)',
    '1G': 'Galileo (International)',
    '1L': 'CitizenPlane (International)',
    '1N': 'Navitaire (International)',
    '1S': 'Sabre (International)',
    '2B': 'Aerocondor (Portugal)',
    '2C': 'SNCF (France)',
    '2G': 'Angara Airlines (Russie)',
    '2J': 'Air Burkina (Burkina Faso)',
    '2L': 'Helvetic Airways (Suisse)',
    '2P': 'PAL Express (Philippines)',
    '2T': 'TruJet (Inde)',
    '3H': 'Air Inuit (Canada)',
    '3K': 'Jetstar Asia (Singapour)',
    '3L': 'Air Arabia Abu Dhabi (Émirats arabes unis)',
    '3M': 'Silver Airways (États-Unis)',
    '3N': 'Air Urga (Ukraine)',
    '3O': 'Air Arabia Maroc (Maroc)',
    '3Q': 'China Yunnan Airlines (Chine)',
    '3R': 'Air Moldova (Moldavie)',
    '3S': 'AeroLogic (Allemagne)',
    '3U': 'Sichuan Airlines (Chine)',
    '3V': 'ASL Airlines Belgium (Belgique)',
    '3X': 'Japan Air Commuter (Japon)',
    '3Y': 'Kartika Airlines (Indonésie)',
    '4A': 'Air Kiribati (Kiribati)',
    '4D': 'Air Sinai (Égypte)',
    '4G': 'Shenzhen Airlines (Chine)',
    '4H': 'United Airways (Bangladesh)',
    '4O': 'Interjet (Mexique)',
    '4P': 'Business Aviation (Congo)',
    '4U': 'Germanwings (Allemagne)',
    '4Y': 'EW Discover (Allemagne)',
    '4Z': 'South African Airlink (Afrique du Sud)',
    '4W': 'Allied Air (Nigéria)',
    '5B': 'Bassaka Air (Cambodge)',
    '5C': 'CAL Cargo Airlines (Israël)',
    '5F': 'FlyOne (Moldavie)',
    '5J': 'Cebu Pacific (Philippines)',
    '5K': 'Hi Fly (Portugal)',
    '5O': 'ASL Airlines France (France)',
    '5P': 'SkyEurope Airlines (Hongrie)',
    '5Q': 'Euroceltic Airways (Irlande)',
    '5V': 'Lviv Airlines (Ukraine)',
    '5W': 'Astraeus (Royaume-Uni)',
    '5X': 'UPS Airlines (États-Unis)',
    '5Y': 'Atlas Air (États-Unis)',
    '5Z': 'CemAir (Afrique du Sud)',
    '6A': 'Aviacsa (Mexique)',
    '6B': 'TUIfly Nordic (Suède)',
    '6E': 'IndiGo (Inde)',
    '6H': 'Israir Airlines (Israël)',
    '6J': 'Solaseed Air (Japon)',
    '6M': 'OnAir (Italie)',
    '6P': 'Dacair Romanian Airlines (Roumanie)',
    '6R': 'Alrosa Air (Russie)',
    '6T': 'Air Mandalay (Birmanie)',
    '6U': 'Air Ukraine (Ukraine)',
    '6W': 'Saravia (Russie)',
    '6Z': 'Ukrainian Cargo Airways (Ukraine)',
    '6V': 'Air Vegas (États-Unis)',
    '7A': 'Express Air Cargo (Tunisie)',
    '7B': 'KrasAir (Russie)',
    '7C': 'Jeju Air (Corée du Sud)',
    '7F': 'First Air (Canada)',
    '7I': 'Insel Air (Curaçao)',
    '7J': 'Tajik Air (Tadjikistan)',
    '7K': 'Kogalymavia (Russie)',
    '7L': 'Sun d\'Or International Airlines (Israël)',
    '7P': 'Air Panama (Panama)',
    '7Q': 'Pawa Dominicana (République dominicaine)',
    '8A': 'Atlas Blue (Maroc)',
    '8I': 'MyAir (Italie)',
    '8J': 'Jet4you (Maroc)',
    '8M': 'Myanmar Airways International (Birmanie)',
    '8Q': 'Onur Air (Turquie)',
    '8R': 'Sol Líneas Aéreas (Argentine)',
    '8Z': 'Congo Airways (République démocratique du Congo)',
    '8U': 'Afriqiyah Airways (Libye)',
    '9B': 'AccesRail (Canada)',
    '9D': 'Toumaï Air Tchad (Tchad)',
    '9I': 'Alliance Air (Inde)',
    '9K': 'Cape Air (États-Unis)',
    '9R': 'Phuket Air (Thaïlande)',
    '9U': 'Air Moldova (Moldavie)',
    '9W': 'Jet Airways (Inde)',
    '9X': 'Southern Airways Express (États-Unis)'
}
